data1 <- read.csv("household_power_consumption.txt", header=TRUE, sep=';',nrows=2075259, na.strings="?", check.names=F, stringsAsFactors=FALSE, comment.char="", quote='\"')
data1$Date <- as.Date(data1$Date, format="%d/%m/%Y")
data <- subset(data1, Date >= "2007-02-01" & Date <= "2007-02-02")
datetime <- paste(as.Date(data$Date), data$Time)
data$Datetime <- as.POSIXct(datetime)
dev.new(width=480, height=480, unit="px")
hist(data$Global_active_power, main="Global Active Power", xlab="Global Active Power (kilowatts)", ylab="Frequency", col="Red")
dev.off()
